services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
      MYSQL_USER: book_user
      MYSQL_PASSWORD: book_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - book-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "book_user", "-p book_pass" ]
      interval: 30s
      retries: 5
      timeout: 10s

  book-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://mysql-db:3306/bookdb
      DATABASE_USER: book_user
      DATABASE_PASSWORD: book_pass
    networks:
      - book-network

networks:
  book-network:
    driver: bridge
    name: book-network

volumes:
  mysql-data:
    driver: local
